### ISSUE TITLE
How to install this app?

### ISSUE THREAD

**Issue by torbdahl** [SoftBankRoboticsEurope/maplocalizeandmove#4]
I'm new to Android development and I'm working with a Pepper robot. How do I actually get the code from your github onto Pepper as an installed app? 

Do we have to use Softbank's Command Center?

**Comment by renythomas** [comment]
Hi, if you just want to install this app, you can use Command Center Store.
Otherwise you can clone this project in android studio (you need to install the pepper plugin for Android studio too:https://developer.softbankrobotics.com/pepper-qisdk/getting-started).
Then connect to the tablet of Pepper then launch the install.

**Comment by torbdahl** [comment]
Thanks for the reply. For reference, my problem was that no Run/Debug configuration showed up in Android Studio after cloning your repo. The following rather hacky solution fixed it: [https://stackoverflow.com/questions/29087882/android-studio-run-debug-configuration-error-module-not-specified](url)
